name: Check Prettier Syntax

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  check-prettier-syntax:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set node to v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm i

      - name: Check code syntax
        run: npm run syntax-check
